FROM golang:1.12-alpine as builder
RUN apk --no-cache add make git
WORKDIR /
COPY . /
RUN make linux

FROM bats/bats:v1.1.0
COPY --from=builder /bin/linux/amd64/kubeval /usr/local/bin
COPY acceptance.bats /acceptance.bats
COPY fixtures /fixtures
RUN "/acceptance.bats"
